export { default as Home } from './Home'
export { default as Register } from './Register'
export { default as Album } from './Album'
export { default as Friends } from './Friends'
export { default as AddFriend } from './AddFriend'
export { default as FriendInfo } from './FriendInfo'
export { default as Public } from './Public'
